### ISSUE TITLE
[1.18.2] Worn notebook entries appear incomplete

### ISSUE THREAD

**Issue by tomko157** [dkmk100/ArsOmega#5]
![2022-05-03_19 31 35](https://user-images.githubusercontent.com/32019796/166508231-48240c9b-dcfe-4c8a-94b1-7967972cf740.png)

There are no entries in the book from Ars omega and I don't know how to proceed with anything :(

**Comment by dkmk100** [comment]
This is a known bug, which I believe I fixed in version 2.2. Can you update and see if it fixes the problem? if not, please let me know so I can look further into it...
As for the information there, I can share the basics of the demon realm:
-you enter by doing the ritual of banishment, which costs a lot of source
-you leave by standing on a rift, yellow cracks in the world
-you find an ore there which is used in some crafting
-the main useful item is the demonic crystal, obtained by killing the boss.
-the boss can be summoned with an item found in a loot chest in a stone brick structure

**Comment by tomko157** [comment]
Hello once again.

The issue is mostly fixed, but there are still some minor issues. Sometimes the text just cuts out in the middle of a sentence or there are no future references in some chapters (for example here with arcane cloth).

![2022-05-03_22 21 20](https://user-images.githubusercontent.com/32019796/166560124-1852e779-577d-4814-a3fb-ba5054b02e94.png)
![2022-05-03_22 24 05](https://user-images.githubusercontent.com/32019796/166560131-35b292cc-4572-4800-aa80-7762110b72ff.png)

**Comment by dkmk100** [comment]
I see. I'll look into fixing up the pages, but since the most improtant info shows up I'll be prioritizing other issues.

**Comment by dkmk100** [comment]
I'm pretty sure I've fixed most of these, but I'll leave this open so anyone can feel free to comment more odd or missing enties they find.
